// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.download.attempts", 0);
user_pref("app.update.elevate.attempts", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1706613750);
user_pref("app.update.lastUpdateTime.background-update-timer", 1706533946);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1706533826);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1706608245);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1706534066);
user_pref("app.update.postupdate", true);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.dom.window.dump.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.lastAppBuildId", "20231102180158");
user_pref("extensions.lastAppVersion", "6.0.30");
user_pref("extensions.lastPlatformVersion", "60.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.zotero.dataDir", "/home/heiarii/Zotero");
user_pref("extensions.zotero.export.bibliographySettings", "{\"mode\":\"citations\",\"method\":\"copy-to-clipboard\"}");
user_pref("extensions.zotero.export.lastStyle", "http://www.zotero.org/styles/elsevier-harvard");
user_pref("extensions.zotero.export.translatorSettings", "{\"exportNotes\":true,\"exportFileData\":true,\"includeAnnotations\":true}");
user_pref("extensions.zotero.feeds.lastTranslationTarget", "C7");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.lastViewedFolder", "C46");
user_pref("extensions.zotero.newItemTypeMRU", "forumPost,journalArticle");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\",\"width\":\"240\"},\"zotero-collections-pane\":{},\"zotero-tags-splitter\":{},\"zotero-tag-selector-container\":{},\"zotero-collections-splitter\":{},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-pane\":{\"width\":\"538\"},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"408\",\"height\":\"300\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-pane\":{\"width\":\"0\"},\"zotero-context-splitter-stacked\":{\"state\":\"open\"},\"zotero-context-pane-inner\":{}}");
user_pref("extensions.zotero.prefVersion", 6);
user_pref("extensions.zotero.purge.tags", true);
user_pref("extensions.zotero.recentSaveTargets", "[{\"id\":\"C14\",\"sessionID\":\"s4VV8rms\"},{\"id\":\"C19\",\"sessionID\":\"HB6637j1\"},{\"id\":\"C25\",\"sessionID\":\"KYq7nq8c\"},{\"id\":\"C45\",\"sessionID\":\"6fOLcEpv\"},{\"id\":\"C4\",\"sessionID\":\"8pdAsHoN\"},{\"id\":\"C24\",\"sessionID\":\"1v8h9XnL\"},{\"id\":\"C46\",\"sessionID\":\"9F7Lmtze\"}]");
user_pref("extensions.zotero.sourceList.persist", "{\"L1\":true,\"C7\":true,\"P1\":false,\"C8\":true,\"C1\":true,\"C12\":true,\"C20\":true,\"L2\":true,\"C14\":true,\"C4\":true}");
user_pref("extensions.zotero.sync.reminder.setUp.enabled", false);
user_pref("extensions.zotero.sync.reminder.setUp.lastDisplayed", 1698318037);
user_pref("extensions.zotero.sync.server.username", "heiariilouchao");
user_pref("extensions.zotero.sync.storage.enabled", false);
user_pref("extensions.zotero.sync.storage.groups.enabled", false);
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormatEditing", "auth.lower + shorttitle(3,3) + year");
user_pref("extensions.zotero.translators.better-bibtex.path.git", "/usr/bin/git");
user_pref("extensions.zotero.translators.better-bibtex.path.texstudio", "");
user_pref("extensions.zotero.translators.better-bibtex.platform", "lin");
user_pref("extensions.zotero.useDataDir", true);
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1706533943);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("places.database.lastMaintenance", 1706533943);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1704374357);
